vich_uploader:
    db_driver: orm

    mappings:
       game_log_file:
           uri_prefix: /games/logs
           upload_destination: '%kernel.project_dir%/public/games/logs'
           namer:
                service: vich_uploader.namer_uniqid